[package]
name = "dockerps-web-frontend"
version = "0.2.0"
authors = ["Naoki Ikeguchi <root@siketyan.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
yew = "0.17"
wasm-bindgen = "0.2"
